# ---------- UI ----------
base.url=https://www.saucedemo.com/
browser=chrome
headless=false
explicit.wait=10

# Public demo credentials published on saucedemo.com
valid.username=standard_user
valid.password=secret_sauce

# ---------- API ----------
api.base.url=https://jsonplaceholder.typicode.com
